name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip autoconf libtool libtool-bin m4 pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libncurses-dev cmake libffi-dev libssl-dev

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools-version: 33.0.0

    - name: Install Python packages
      run: |
        pip install --user --upgrade buildozer cython virtualenv

    - name: Build with Buildozer
      run: |
        buildozer -v android debug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
